### PR TITLE
Feat/support batch request

### PR DESCRIPTION
**Pull request by hunjixin**

### CODE REVIEW

**Review by magik6k — COMMENTED** [review]
What's the advantage of this over sending multiple requests with different ids over a single websocket in parallel? Is this much faster (how much?)?

**Comment by hunjixin** [comment]
> r

Websocket won't improve much, but in http's case, a high frequency of requests can result in client errors.

**Comment by hunjixin** [comment]
> What's the advantage of this over sending multiple requests with different ids over a single websocket in parallel? Is this much faster (how much?)?

Websocket won't improve much, but in http's case, a high frequency of requests can result in client errors.

**Comment by Stebalien** [comment]
> Websocket won't improve much

The websocket transport allows one to send multiple RPCs in parallel over the same connection. That should _effectively_ act as a batch request.

> but in http's case, a high frequency of requests can result in client errors.

If you need high-throughput requests, please use the websocket transport and avoid making HTTP requests.

**Comment by hunjixin** [comment]
The code doesn't work very well at the time, and I'll describe the problem I'm having.

**Pull request closed without merging**
