### PR TITLE
test: initial ipdx unified-ci config

### PR DESCRIPTION
**Pull request by rvagg**
Ref: https://github.com/filecoin-project/go-jsonrpc/issues/109

Just seeing what this would look like when run. Proper enablement just means adding `web3-bot` to a the list of users that can access this repo and it'll do the updating.

### CODE REVIEW

**Comment by rvagg** [comment]
* Bumped go version to 1.21
* Removed CircleCI config

staticcheck error fixed @ https://github.com/filecoin-project/go-jsonrpc/pull/111

**Comment by rvagg** [comment]
ooops, forgot to actually add the actions from unified-ci here, done now

**Comment by rvagg** [comment]
pulled in #111

**Review by rjan90 — APPROVED** [review]

**Review by aarshkshah1992 — APPROVED** [review]

**Comment by aarshkshah1992** [comment]
I think we need to remove CircleCI now ?

**Comment by rvagg** [comment]
circleci webhook removed, `@web3-bot` write access added, should be good to go now

**Pull request merged**
